[game]

seed_deck = 42
seed_priority = 0
min_players = 3
max_players = 6
points_for_guessing_correctly = 20
points_for_successful_trick = 10
points_for_unsuccessfuly_trick = -10

[deck]

# cards:
# 1 - 13 blue
# 1 - 13 green
# 1 - 13 red
# 1 - 13 yellow
# 4 Fool
# 4 Wizard

n_cards_per_suit = 13
n_suits = 4
suits = ['B', 'G', 'R', 'Y']

[deck.special_cards.N] # fools
name = 'N'
count = 4

[deck.special_cards.Z] # wizards
name = 'Z'
count = 4

[agent]

weight_temperature = 50

base_lead_growth_per_trick = 2.0
alpha = 3.0
softmin_sharpness =  0.05
growth_temperature = 20.0
growth_penalty = 0.75
position_temperature = 30.0
position_penalty = 0.40
growth_weight = 1.0
position_weight = 0.75
win_reward =  100.0
