[game]

seed_deck = 42
seed_priority = 0
min_players = 3
max_players = 6
points_for_guessing_correctly = 20
points_for_successful_trick = 10
points_for_unsuccessfuly_trick = -10

[deck]

# cards:
# 1 - 13 blue
# 1 - 13 green
# 1 - 13 red
# 1 - 13 yellow
# 4 Fool
# 4 Wizard

n_cards_per_suit = 13
n_suits = 4
suits = ['B', 'G', 'R', 'Y']

[deck.special_cards.N] # fools
name = 'N'
count = 4

[deck.special_cards.Z] # wizards
name = 'Z'
count = 4

[agent]
# probability to explore random moves

weight_temperature = 50
score_difference_weight = 10
round_scores_weight = 1
